-- MEETING POINT 5 (Plains Village)
-- Auto-generated from Minecraft Wiki blueprints
-- Reference: https://minecraft.wiki/w/Village/Structure/Blueprints
return {
    name = "MEETING POINT 5",
    w = 10, d = 8, h = 5,
    doorPos = {x=5, y=0, z=0},
    tags = {"social", "village"},
    blocks = (function()
        local b = {}
        local function add(x,y,z,t,f,h,s)
            local entry = {x=x, y=y, z=z, t=t}
            if f then entry.f = f end
            if h then entry.h = h end
            if s then entry.s = s end
            b[#b+1] = entry
        end

        add(0,0,0,"cobblestone")
        add(1,0,0,"cobblestone")
        add(2,0,0,"cobblestone")
        add(3,0,0,"cobblestone")
        add(4,0,0,"cobblestone")
        add(5,0,0,"cobblestone")
        add(6,0,0,"cobblestone")
        add(7,0,0,"cobblestone")
        add(8,0,0,"cobblestone")
        add(9,0,0,"cobblestone")
        add(0,0,1,"cobblestone")
        add(1,0,1,"cobblestone")
        add(2,0,1,"cobblestone")
        add(3,0,1,"cobblestone")
        add(4,0,1,"cobblestone")
        add(5,0,1,"cobblestone")
        add(6,0,1,"cobblestone")
        add(7,0,1,"cobblestone")
        add(8,0,1,"cobblestone")
        add(9,0,1,"cobblestone")
        add(0,0,2,"cobblestone")
        add(1,0,2,"cobblestone")
        add(2,0,2,"cobblestone")
        add(3,0,2,"cobblestone")
        add(4,0,2,"cobblestone")
        add(5,0,2,"cobblestone")
        add(6,0,2,"cobblestone")
        add(7,0,2,"cobblestone")
        add(8,0,2,"cobblestone")
        add(9,0,2,"cobblestone")
        add(0,0,3,"cobblestone")
        add(1,0,3,"cobblestone")
        add(2,0,3,"cobblestone")
        add(3,0,3,"cobblestone")
        add(4,0,3,"cobblestone")
        add(5,0,3,"cobblestone")
        add(6,0,3,"cobblestone")
        add(7,0,3,"cobblestone")
        add(8,0,3,"cobblestone")
        add(9,0,3,"cobblestone")
        add(0,0,4,"cobblestone")
        add(1,0,4,"cobblestone")
        add(2,0,4,"cobblestone")
        add(3,0,4,"cobblestone")
        add(4,0,4,"cobblestone")
        add(5,0,4,"cobblestone")
        add(6,0,4,"cobblestone")
        add(7,0,4,"cobblestone")
        add(8,0,4,"cobblestone")
        add(9,0,4,"cobblestone")
        add(0,0,5,"cobblestone")
        add(1,0,5,"cobblestone")
        add(2,0,5,"cobblestone")
        add(3,0,5,"cobblestone")
        add(4,0,5,"cobblestone")
        add(5,0,5,"cobblestone")
        add(6,0,5,"cobblestone")
        add(7,0,5,"cobblestone")
        add(8,0,5,"cobblestone")
        add(9,0,5,"cobblestone")
        add(0,0,6,"cobblestone")
        add(1,0,6,"cobblestone")
        add(2,0,6,"cobblestone")
        add(3,0,6,"cobblestone")
        add(4,0,6,"cobblestone")
        add(5,0,6,"cobblestone")
        add(6,0,6,"cobblestone")
        add(7,0,6,"cobblestone")
        add(8,0,6,"cobblestone")
        add(9,0,6,"cobblestone")
        add(0,0,7,"cobblestone")
        add(1,0,7,"cobblestone")
        add(2,0,7,"cobblestone")
        add(3,0,7,"cobblestone")
        add(4,0,7,"cobblestone")
        add(5,0,7,"cobblestone")
        add(6,0,7,"cobblestone")
        add(7,0,7,"cobblestone")
        add(8,0,7,"cobblestone")
        add(9,0,7,"cobblestone")
        add(2,1,2,"oak_fence")
        add(7,1,2,"oak_fence")
        add(2,1,3,"oak_fence")
        add(3,1,3,"oak_planks")
        add(4,1,3,"oak_planks")
        add(5,1,3,"oak_planks")
        add(6,1,3,"oak_planks")
        add(7,1,3,"oak_fence")
        add(2,1,4,"oak_fence")
        add(3,1,4,"oak_planks")
        add(4,1,4,"oak_planks")
        add(5,1,4,"oak_planks")
        add(6,1,4,"oak_planks")
        add(7,1,4,"oak_fence")
        add(2,1,5,"oak_fence")
        add(7,1,5,"oak_fence")
        add(2,2,2,"oak_fence")
        add(7,2,2,"oak_fence")
        add(2,2,3,"oak_fence")
        add(7,2,3,"oak_fence")
        add(2,2,4,"oak_fence")
        add(7,2,4,"oak_fence")
        add(2,2,5,"oak_fence")
        add(7,2,5,"oak_fence")
        add(2,3,2,"oak_fence")
        add(7,3,2,"oak_fence")
        add(2,3,3,"oak_fence")
        add(5,3,3,"bell")
        add(7,3,3,"oak_fence")
        add(2,3,4,"oak_fence")
        add(7,3,4,"oak_fence")
        add(2,3,5,"oak_fence")
        add(7,3,5,"oak_fence")
        add(2,4,2,"oak_slab")
        add(3,4,2,"oak_slab")
        add(4,4,2,"oak_slab")
        add(5,4,2,"oak_slab")
        add(6,4,2,"oak_slab")
        add(7,4,2,"oak_slab")
        add(2,4,3,"oak_slab")
        add(3,4,3,"oak_planks")
        add(4,4,3,"oak_planks")
        add(5,4,3,"oak_planks")
        add(6,4,3,"oak_planks")
        add(7,4,3,"oak_slab")
        add(2,4,4,"oak_slab")
        add(3,4,4,"oak_planks")
        add(4,4,4,"oak_planks")
        add(5,4,4,"oak_planks")
        add(6,4,4,"oak_planks")
        add(7,4,4,"oak_slab")
        add(2,4,5,"oak_slab")
        add(3,4,5,"oak_slab")
        add(4,4,5,"oak_slab")
        add(5,4,5,"oak_slab")
        add(6,4,5,"oak_slab")
        add(7,4,5,"oak_slab")
        add(3,4,2,"torch")
        add(6,4,5,"torch")
        add(7,4,2,"torch")

        return b
    end)()
}
