-- MEETING POINT 1 (Plains Village)
-- Auto-generated from Minecraft Wiki blueprints
-- Reference: https://minecraft.wiki/w/Village/Structure/Blueprints
return {
    name = "MEETING POINT 1",
    w = 6, d = 6, h = 7,
    doorPos = {x=3, y=0, z=0},
    tags = {"social", "village"},
    blocks = (function()
        local b = {}
        local function add(x,y,z,t,f,h,s)
            local entry = {x=x, y=y, z=z, t=t}
            if f then entry.f = f end
            if h then entry.h = h end
            if s then entry.s = s end
            b[#b+1] = entry
        end

        add(0,0,0,"cobblestone")
        add(1,0,0,"cobblestone")
        add(2,0,0,"cobblestone")
        add(3,0,0,"cobblestone")
        add(4,0,0,"cobblestone")
        add(5,0,0,"cobblestone")
        add(0,0,1,"cobblestone")
        add(1,0,1,"cobblestone")
        add(2,0,1,"cobblestone")
        add(3,0,1,"cobblestone")
        add(4,0,1,"cobblestone")
        add(5,0,1,"cobblestone")
        add(0,0,2,"cobblestone")
        add(1,0,2,"cobblestone")
        add(4,0,2,"cobblestone")
        add(5,0,2,"cobblestone")
        add(0,0,3,"cobblestone")
        add(1,0,3,"cobblestone")
        add(4,0,3,"cobblestone")
        add(5,0,3,"cobblestone")
        add(0,0,4,"cobblestone")
        add(1,0,4,"cobblestone")
        add(2,0,4,"cobblestone")
        add(3,0,4,"cobblestone")
        add(4,0,4,"cobblestone")
        add(5,0,4,"cobblestone")
        add(0,0,5,"cobblestone")
        add(1,0,5,"cobblestone")
        add(2,0,5,"cobblestone")
        add(3,0,5,"cobblestone")
        add(4,0,5,"cobblestone")
        add(5,0,5,"cobblestone")
        add(0,1,0,"cobblestone")
        add(1,1,0,"cobblestone")
        add(2,1,0,"cobblestone")
        add(3,1,0,"cobblestone")
        add(4,1,0,"cobblestone")
        add(5,1,0,"cobblestone")
        add(0,1,1,"cobblestone")
        add(1,1,1,"cobblestone")
        add(4,1,1,"cobblestone")
        add(5,1,1,"cobblestone")
        add(0,1,2,"cobblestone")
        add(1,1,2,"cobblestone")
        add(4,1,2,"cobblestone")
        add(5,1,2,"cobblestone")
        add(0,1,3,"cobblestone")
        add(1,1,3,"cobblestone")
        add(2,1,3,"cobblestone")
        add(3,1,3,"cobblestone")
        add(4,1,3,"cobblestone")
        add(5,1,3,"cobblestone")
        add(0,1,4,"cobblestone")
        add(1,1,4,"cobblestone")
        add(2,1,4,"cobblestone")
        add(3,1,4,"cobblestone")
        add(4,1,4,"cobblestone")
        add(5,1,4,"cobblestone")
        add(0,1,5,"cobblestone")
        add(1,1,5,"cobblestone")
        add(2,1,5,"cobblestone")
        add(3,1,5,"cobblestone")
        add(4,1,5,"cobblestone")
        add(5,1,5,"cobblestone")
        add(0,2,0,"cobblestone")
        add(1,2,0,"cobblestone")
        add(2,2,0,"cobblestone")
        add(3,2,0,"cobblestone")
        add(4,2,0,"cobblestone")
        add(5,2,0,"cobblestone")
        add(0,2,1,"cobblestone")
        add(5,2,1,"cobblestone")
        add(0,2,2,"cobblestone")
        add(3,2,2,"bell")
        add(5,2,2,"cobblestone")
        add(0,2,3,"cobblestone")
        add(5,2,3,"cobblestone")
        add(0,2,4,"cobblestone")
        add(5,2,4,"cobblestone")
        add(0,2,5,"cobblestone")
        add(1,2,5,"cobblestone")
        add(2,2,5,"cobblestone")
        add(3,2,5,"cobblestone")
        add(4,2,5,"cobblestone")
        add(5,2,5,"cobblestone")
        add(0,3,0,"oak_fence")
        add(5,3,0,"oak_fence")
        add(0,3,5,"oak_fence")
        add(5,3,5,"oak_fence")
        add(0,4,0,"oak_fence")
        add(5,4,0,"oak_fence")
        add(0,4,5,"oak_fence")
        add(5,4,5,"oak_fence")
        add(0,5,0,"cobblestone")
        add(1,5,0,"cobblestone")
        add(2,5,0,"cobblestone")
        add(3,5,0,"cobblestone")
        add(4,5,0,"cobblestone")
        add(5,5,0,"cobblestone")
        add(0,5,1,"cobblestone")
        add(1,5,1,"cobblestone")
        add(2,5,1,"cobblestone")
        add(3,5,1,"cobblestone")
        add(4,5,1,"cobblestone")
        add(5,5,1,"cobblestone")
        add(0,5,2,"cobblestone")
        add(1,5,2,"cobblestone")
        add(2,5,2,"cobblestone")
        add(3,5,2,"cobblestone")
        add(4,5,2,"cobblestone")
        add(5,5,2,"cobblestone")
        add(0,5,3,"cobblestone")
        add(1,5,3,"cobblestone")
        add(2,5,3,"cobblestone")
        add(3,5,3,"cobblestone")
        add(4,5,3,"cobblestone")
        add(5,5,3,"cobblestone")
        add(0,5,4,"cobblestone")
        add(1,5,4,"cobblestone")
        add(2,5,4,"cobblestone")
        add(3,5,4,"cobblestone")
        add(4,5,4,"cobblestone")
        add(5,5,4,"cobblestone")
        add(0,5,5,"cobblestone")
        add(1,5,5,"cobblestone")
        add(2,5,5,"cobblestone")
        add(3,5,5,"cobblestone")
        add(4,5,5,"cobblestone")
        add(5,5,5,"cobblestone")
        add(0,6,0,"torch")
        add(5,6,0,"torch")
        add(0,6,5,"torch")
        add(5,6,5,"torch")

        return b
    end)()
}
