-- MEETING POINT 3 (Plains Village)
-- Auto-generated from Minecraft Wiki blueprints
-- Reference: https://minecraft.wiki/w/Village/Structure/Blueprints
return {
    name = "MEETING POINT 3",
    w = 9, d = 9, h = 9,
    doorPos = {x=4, y=0, z=0},
    tags = {"social", "village"},
    blocks = (function()
        local b = {}
        local function add(x,y,z,t,f,h,s)
            local entry = {x=x, y=y, z=z, t=t}
            if f then entry.f = f end
            if h then entry.h = h end
            if s then entry.s = s end
            b[#b+1] = entry
        end

        add(0,0,0,"cobblestone")
        add(1,0,0,"cobblestone")
        add(2,0,0,"cobblestone")
        add(3,0,0,"cobblestone")
        add(4,0,0,"cobblestone")
        add(5,0,0,"cobblestone")
        add(6,0,0,"cobblestone")
        add(7,0,0,"cobblestone")
        add(8,0,0,"cobblestone")
        add(0,0,1,"cobblestone")
        add(1,0,1,"cobblestone")
        add(2,0,1,"cobblestone")
        add(3,0,1,"cobblestone")
        add(4,0,1,"cobblestone")
        add(5,0,1,"cobblestone")
        add(6,0,1,"cobblestone")
        add(7,0,1,"cobblestone")
        add(8,0,1,"cobblestone")
        add(0,0,2,"cobblestone")
        add(1,0,2,"cobblestone")
        add(2,0,2,"cobblestone")
        add(3,0,2,"cobblestone")
        add(4,0,2,"cobblestone")
        add(5,0,2,"cobblestone")
        add(6,0,2,"cobblestone")
        add(7,0,2,"cobblestone")
        add(8,0,2,"cobblestone")
        add(0,0,3,"cobblestone")
        add(1,0,3,"cobblestone")
        add(2,0,3,"cobblestone")
        add(3,0,3,"cobblestone")
        add(4,0,3,"cobblestone")
        add(5,0,3,"cobblestone")
        add(6,0,3,"cobblestone")
        add(7,0,3,"cobblestone")
        add(8,0,3,"cobblestone")
        add(0,0,4,"cobblestone")
        add(1,0,4,"cobblestone")
        add(2,0,4,"cobblestone")
        add(3,0,4,"cobblestone")
        add(4,0,4,"cobblestone")
        add(5,0,4,"cobblestone")
        add(6,0,4,"cobblestone")
        add(7,0,4,"cobblestone")
        add(8,0,4,"cobblestone")
        add(0,0,5,"cobblestone")
        add(1,0,5,"cobblestone")
        add(2,0,5,"cobblestone")
        add(3,0,5,"cobblestone")
        add(4,0,5,"cobblestone")
        add(5,0,5,"cobblestone")
        add(6,0,5,"cobblestone")
        add(7,0,5,"cobblestone")
        add(8,0,5,"cobblestone")
        add(0,0,6,"cobblestone")
        add(1,0,6,"cobblestone")
        add(2,0,6,"cobblestone")
        add(3,0,6,"cobblestone")
        add(4,0,6,"cobblestone")
        add(5,0,6,"cobblestone")
        add(6,0,6,"cobblestone")
        add(7,0,6,"cobblestone")
        add(8,0,6,"cobblestone")
        add(0,0,7,"cobblestone")
        add(1,0,7,"cobblestone")
        add(2,0,7,"cobblestone")
        add(3,0,7,"cobblestone")
        add(4,0,7,"cobblestone")
        add(5,0,7,"cobblestone")
        add(6,0,7,"cobblestone")
        add(7,0,7,"cobblestone")
        add(8,0,7,"cobblestone")
        add(0,0,8,"cobblestone")
        add(1,0,8,"cobblestone")
        add(2,0,8,"cobblestone")
        add(3,0,8,"cobblestone")
        add(4,0,8,"cobblestone")
        add(5,0,8,"cobblestone")
        add(6,0,8,"cobblestone")
        add(7,0,8,"cobblestone")
        add(8,0,8,"cobblestone")
        add(4,1,0,"cobblestone_stairs","south","bottom")
        add(2,1,1,"cobblestone_stairs","east","bottom")
        add(4,1,1,"oak_fence")
        add(6,1,1,"cobblestone_stairs","west","bottom")
        add(2,1,2,"cobblestone_stairs","east","bottom")
        add(6,1,2,"cobblestone_stairs","west","bottom")
        add(2,1,3,"cobblestone_stairs","east","bottom")
        add(4,1,3,"oak_log")
        add(6,1,3,"cobblestone_stairs","west","bottom")
        add(4,1,5,"cobblestone_stairs","north","bottom")
        add(4,1,6,"oak_fence")
        add(2,1,5,"cobblestone_stairs","east","bottom")
        add(6,1,5,"cobblestone_stairs","west","bottom")
        add(4,1,1,"oak_fence")
        add(4,1,5,"oak_fence")
        add(2,2,1,"oak_fence")
        add(6,2,1,"oak_fence")
        add(4,2,3,"oak_log")
        add(2,2,5,"oak_fence")
        add(6,2,5,"oak_fence")
        add(2,3,1,"oak_fence")
        add(4,3,1,"bell")
        add(6,3,1,"oak_fence")
        add(4,3,3,"oak_log")
        add(2,3,5,"oak_fence")
        add(4,3,5,"bell")
        add(6,3,5,"oak_fence")
        add(1,3,3,"torch")
        add(3,3,3,"torch")
        add(5,3,3,"torch")
        add(7,3,3,"torch")
        add(4,4,3,"oak_log")
        add(2,4,1,"cobblestone")
        add(3,4,1,"cobblestone")
        add(4,4,1,"cobblestone")
        add(5,4,1,"cobblestone")
        add(6,4,1,"cobblestone")
        add(2,4,5,"cobblestone")
        add(3,4,5,"cobblestone")
        add(4,4,5,"cobblestone")
        add(5,4,5,"cobblestone")
        add(6,4,5,"cobblestone")
        add(4,4,2,"cobblestone")
        add(4,4,4,"cobblestone")
        add(4,5,3,"oak_log")
        add(3,5,2,"leaves")
        add(4,5,2,"leaves")
        add(5,5,2,"leaves")
        add(3,5,3,"leaves")
        add(5,5,3,"leaves")
        add(3,5,4,"leaves")
        add(4,5,4,"leaves")
        add(5,5,4,"leaves")
        add(4,6,3,"oak_log")
        add(2,6,1,"leaves")
        add(3,6,1,"leaves")
        add(4,6,1,"leaves")
        add(5,6,1,"leaves")
        add(6,6,1,"leaves")
        add(2,6,2,"leaves")
        add(3,6,2,"leaves")
        add(4,6,2,"leaves")
        add(5,6,2,"leaves")
        add(6,6,2,"leaves")
        add(2,6,3,"leaves")
        add(3,6,3,"leaves")
        add(5,6,3,"leaves")
        add(6,6,3,"leaves")
        add(2,6,4,"leaves")
        add(3,6,4,"leaves")
        add(4,6,4,"leaves")
        add(5,6,4,"leaves")
        add(6,6,4,"leaves")
        add(2,6,5,"leaves")
        add(3,6,5,"leaves")
        add(4,6,5,"leaves")
        add(5,6,5,"leaves")
        add(6,6,5,"leaves")
        add(3,7,2,"leaves")
        add(4,7,2,"leaves")
        add(5,7,2,"leaves")
        add(3,7,3,"leaves")
        add(4,7,3,"leaves")
        add(5,7,3,"leaves")
        add(3,7,4,"leaves")
        add(4,7,4,"leaves")
        add(5,7,4,"leaves")
        add(4,8,3,"leaves")

        return b
    end)()
}
