-- SMALL_HOUSE_8 (Plains Village)
-- Auto-generated from Minecraft Wiki blueprints
-- Reference: https://minecraft.wiki/w/Village/Structure/Blueprints
return {
    name = "SMALL_HOUSE_8",
    w = 5, d = 5, h = 7,
    doorPos = {x=1, y=2, z=3},
    tags = {"small", "cozy", "village"},
    blocks = (function()
        local b = {}
        local function add(x,y,z,t,f,h,s)
            local entry = {x=x, y=y, z=z, t=t}
            if f then entry.f = f end
            if h then entry.h = h end
            if s then entry.s = s end
            b[#b+1] = entry
        end

        add(2,0,0,"oak_log")
        add(3,0,0,"cobblestone")
        add(4,0,0,"cobblestone")
        add(0,0,1,"cobblestone")
        add(1,0,1,"oak_log")
        add(3,0,1,"cobblestone")
        add(4,0,1,"oak_planks")
        add(0,0,2,"oak_planks")
        add(1,0,2,"oak_planks")
        add(2,0,2,"cobblestone")
        add(4,0,2,"cobblestone")
        add(0,0,3,"oak_planks")
        add(1,0,3,"oak_planks")
        add(2,0,3,"oak_planks")
        add(3,0,3,"cobblestone")
        add(0,0,4,"oak_log")
        add(1,0,4,"cobblestone")
        add(2,0,4,"cobblestone")
        add(3,0,4,"cobblestone")
        add(4,0,4,"oak_log")
        add(0,0,4,"cobblestone_stairs","south","bottom")
        add(0,1,0,"oak_log")
        add(1,1,0,"cobblestone")
        add(2,1,0,"cobblestone")
        add(3,1,0,"cobblestone")
        add(4,1,0,"oak_log")
        add(0,1,1,"cobblestone")
        add(1,1,1,"bed")
        add(2,1,1,"oak_stairs","east","bottom")
        add(3,1,1,"cobblestone")
        add(4,1,1,"cobblestone")
        add(0,1,2,"cobblestone")
        add(1,1,2,"cobblestone")
        add(2,1,2,"cobblestone")
        add(3,1,2,"cobblestone")
        add(4,1,2,"oak_log")
        add(0,1,3,"cobblestone")
        add(1,1,3,"door")
        add(2,1,3,"cobblestone")
        add(3,1,3,"oak_log")
        add(0,2,0,"oak_log")
        add(1,2,0,"cobblestone")
        add(2,2,0,"glass_pane")
        add(3,2,0,"cobblestone")
        add(4,2,0,"oak_log")
        add(0,2,1,"cobblestone")
        add(1,2,1,"cobblestone")
        add(2,2,1,"glass_pane")
        add(3,2,1,"glass_pane")
        add(4,2,1,"cobblestone")
        add(0,2,2,"cobblestone")
        add(1,2,2,"oak_log")
        add(2,2,2,"cobblestone")
        add(0,3,0,"oak_log")
        add(1,3,0,"cobblestone")
        add(2,3,0,"cobblestone")
        add(3,3,0,"cobblestone")
        add(4,3,0,"oak_log")
        add(0,3,1,"cobblestone")
        add(1,3,1,"cobblestone")
        add(2,3,1,"cobblestone")
        add(3,3,1,"cobblestone")
        add(4,3,1,"cobblestone")
        add(0,3,2,"cobblestone")
        add(1,3,2,"oak_log")
        add(2,3,2,"cobblestone")
        add(3,3,2,"cobblestone")
        add(4,3,2,"cobblestone")
        add(0,3,3,"oak_log")
        add(1,3,3,"torch")
        add(0,4,0,"oak_stairs","south","bottom")
        add(1,4,0,"oak_stairs","south","bottom")
        add(2,4,0,"oak_stairs","south","bottom")
        add(3,4,0,"oak_stairs","south","bottom")
        add(4,4,0,"oak_stairs","south","bottom")
        add(0,4,1,"oak_log")
        add(1,4,1,"oak_log")
        add(2,4,1,"oak_log")
        add(3,4,1,"oak_log")
        add(4,4,1,"oak_log")
        add(0,4,2,"oak_stairs","north","bottom")
        add(1,4,2,"oak_planks")
        add(2,4,2,"oak_planks")
        add(3,4,2,"oak_stairs","north","bottom")
        add(4,4,2,"oak_stairs","north","bottom")
        add(0,5,0,"oak_stairs","south","bottom")
        add(1,5,0,"oak_stairs","south","bottom")
        add(2,5,0,"oak_stairs","south","bottom")
        add(3,5,0,"oak_stairs","south","bottom")
        add(4,5,0,"oak_stairs","south","bottom")
        add(0,5,1,"oak_planks")
        add(1,5,1,"oak_planks")
        add(2,5,1,"oak_planks")
        add(3,5,1,"oak_planks")
        add(4,5,1,"oak_planks")
        add(0,5,2,"oak_stairs","north","bottom")
        add(1,5,2,"oak_stairs","north","bottom")
        add(2,5,2,"oak_stairs","north","bottom")
        add(3,5,2,"oak_stairs","north","bottom")
        add(4,5,2,"oak_stairs","north","bottom")
        add(0,6,0,"oak_stairs","south","bottom")
        add(1,6,0,"oak_planks")
        add(2,6,0,"oak_stairs","south","bottom")
        add(3,6,0,"oak_stairs","south","bottom")
        add(4,6,0,"oak_planks")
        add(0,6,1,"oak_planks")
        add(1,6,1,"oak_planks")
        add(2,6,1,"oak_planks")
        add(3,6,1,"oak_planks")
        add(4,6,1,"oak_planks")
        add(0,6,2,"oak_stairs","north","bottom")
        add(1,6,2,"oak_planks")
        add(2,6,2,"oak_stairs","north","bottom")
        add(3,6,2,"oak_stairs","north","bottom")
        add(4,6,2,"oak_planks")

        return b
    end)()
}
